### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by hirokimorita** [FlotingDream/Manga-Colorization-FJ#1]
it is throw an error when the Tile after:

```
imwrite_('./output/322.webp'): can't write data: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_webp.cpp:304: error: (-215:Assertion failed) size > 0 in function 'write'
```

please fixed, thanks.

**Comment by FlotingDream** [comment]
It works fine in colab, and in my win10 for default args. what args do you use?
Try to update OpenCV?

my version
>>> import cv2
>>> print (cv2.__version__)
4.6.0
